name: assignment1_2
channels:
  - conda-forge
dependencies:
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - ipykernel=6.29.5
  - jupyter=1.1.1
  - notebook=7.3.2
  - matplotlib=3.10.0
  - scikit-learn=1.6.1
  - pandas=2.2.3
  - python=3.12
  - pip=25.0
  - pip:
      - torch-summary==1.4.5